#!/usr/bin/env python3
"""
llm_client.py -- thin wrapper around the local Open WebUI instance (http://127.0.0.1:3000 by
default) fronting Ollama models, for optionally offloading draft-only work (summarizing,
triage/classification, first-pass "what should I grep for" suggestions) from other mission_toolkit
scripts and agent sessions.

Why this exists / how it must be used: this project's whole methodology runs on citing real
source for every id/binding/mapping -- see DIST_PACKAGING.md and the Assault backport's own
strict-accuracy rule (never invent a path/id/flag, say "don't know" instead of guessing). A local
LLM is a plausible source of exactly that kind of confident-but-wrong guess. Nothing in this module
asserts truth on its own: every call is a DRAFT, and any caller that writes an LLM response into a
real file MUST tag it with LLM_DRAFT_TAG (see below) so it reads as unverified to the next human or
agent that finds it -- the same visual convention already used for `-- DSP-PORT-TODO` markers
elsewhere in this project. Never wire this into anything that writes an id, binding name, or
mapping directly into a shipped package without a human/grep verification step after it.

Auth: reads the API key from (in order) the OPENWEBUI_API_KEY env var, then a local
`.openwebui_key` file next to this script (gitignored -- see .gitignore). Generate a key yourself
in Open WebUI's own UI (Settings -> Account -> API Keys) -- this module never creates one, and
never will (that requires an authenticated browser session this module has no access to).

Usage as a library:
    import llm_client
    text = llm_client.chat("Summarize this in one sentence: ...")
    text = llm_client.chat("...", model="gemma4:26b", system="You are terse.")
    models = llm_client.list_models()

Usage from the command line (quick manual testing, not for scripted use):
    py -3 llm_client.py --list-models
    py -3 llm_client.py --model qwen2.5-coder:7b "Explain what this Lua snippet does: ..."
"""
from __future__ import annotations

import argparse
import json
import os
import sys
import urllib.error
import urllib.request
from pathlib import Path

BASE_URL = os.environ.get("OPENWEBUI_BASE_URL", "http://127.0.0.1:3000").rstrip("/")
KEY_FILE = Path(__file__).resolve().parent / ".openwebui_key"

# Default model: qwen2.5-coder is the best fit of the models currently loaded in this install for
# code/Lua-flavored draft work (binding-pattern flagging, doc summarization of scripts). Override
# per-call via the `model` argument, or pick from list_models() for anything closer to real
# judgment (e.g. gemma4:26b, which also has "thinking").
DEFAULT_MODEL = "qwen2.5-coder:7b"

# Prepend this to any LLM output before it's written into a real file (comment, doc, report) --
# never let a draft suggestion sit unmarked next to hand-verified content. Matches the
# `-- DSP-PORT-TODO` marker convention already used in the Assault backport's converted Lua.
LLM_DRAFT_TAG = "LLM-DRAFT, UNVERIFIED -- generated by a local model, not independently confirmed"


class LLMClientError(RuntimeError):
    """Raised for auth failures, unreachable server, or a malformed response -- never silently
    swallowed, since a caller treating a failed call as an empty-but-successful draft could mask
    a real connectivity/auth problem as "the model had nothing to say"."""


def _load_api_key() -> str:
    env_key = os.environ.get("OPENWEBUI_API_KEY")
    if env_key:
        return env_key.strip()
    if KEY_FILE.exists():
        key = KEY_FILE.read_text(encoding="utf-8").strip()
        if key:
            return key
    raise LLMClientError(
        f"No API key found. Set OPENWEBUI_API_KEY, or write one to {KEY_FILE} "
        "(generate it in Open WebUI's own UI: Settings -> Account -> API Keys)."
    )


def save_api_key(key: str) -> None:
    """Writes the key to KEY_FILE (gitignored). Overwrites whatever was there before -- callers
    (e.g. the Settings page) should treat an empty/whitespace-only submission as "leave the
    existing key alone" and simply not call this, rather than calling it with an empty string."""
    key = key.strip()
    if not key:
        raise LLMClientError("Refusing to save an empty API key.")
    KEY_FILE.write_text(key, encoding="utf-8")


def has_api_key() -> bool:
    """True if a key is resolvable right now (env var or KEY_FILE) -- lets a caller show
    "configured: yes/no" without ever reading the key's actual value back out for display."""
    try:
        _load_api_key()
        return True
    except LLMClientError:
        return False


def _request(path: str, payload: dict | None = None, timeout: float = 60.0,
             base_url: str | None = None) -> dict:
    url = f"{(base_url or BASE_URL).rstrip('/')}{path}"
    key = _load_api_key()
    headers = {"Authorization": f"Bearer {key}"}
    data = None
    if payload is not None:
        headers["Content-Type"] = "application/json"
        data = json.dumps(payload).encode("utf-8")

    req = urllib.request.Request(url, data=data, headers=headers, method="POST" if data else "GET")
    try:
        with urllib.request.urlopen(req, timeout=timeout) as resp:
            return json.loads(resp.read().decode("utf-8"))
    except urllib.error.HTTPError as e:
        body = e.read().decode("utf-8", errors="replace")
        raise LLMClientError(f"HTTP {e.code} from {url}: {body}") from e
    except urllib.error.URLError as e:
        raise LLMClientError(
            f"Could not reach {url} ({e.reason}). Is Open WebUI running?"
        ) from e


def list_models(base_url: str | None = None) -> list[dict]:
    """Every model Open WebUI currently reports (loaded via Ollama or otherwise). Each entry's
    `id` is what `chat(model=...)` expects."""
    result = _request("/api/models", base_url=base_url)
    return result.get("data", [])


def chat_messages(
    messages: list[dict],
    model: str = DEFAULT_MODEL,
    temperature: float = 0.2,
    timeout: float = 60.0,
    base_url: str | None = None,
) -> dict:
    """Lower-level call for a caller that needs to manage its own multi-turn message history
    (e.g. gui_server.py's read-only-DB-tool ReAct loop) -- chat_full() is a thin single-turn
    wrapper around this for everything else. Returns {"content": str, "usage": dict}, same shape
    as chat_full()."""
    payload = {"model": model, "messages": messages, "stream": False, "temperature": temperature}
    result = _request("/api/chat/completions", payload, timeout=timeout, base_url=base_url)

    try:
        content = result["choices"][0]["message"]["content"]
    except (KeyError, IndexError) as e:
        raise LLMClientError(f"Unexpected response shape: {result}") from e

    return {"content": content, "usage": result.get("usage", {})}


def chat_full(
    prompt: str,
    model: str = DEFAULT_MODEL,
    system: str | None = None,
    temperature: float = 0.2,
    timeout: float = 60.0,
    base_url: str | None = None,
    image_b64: str | list[str] | None = None,
) -> dict:
    """One-shot chat completion, returning the full result: {"content": str, "usage": dict}.
    `usage` is Open WebUI's own reported stats for the call (response_token/s, total_duration,
    prompt/completion token counts, etc.) -- whatever it sent back, passed through as-is so a
    caller can show real timing/cost info without this module guessing at a schema.

    `image_b64`: one or more base64-encoded images (no data: URI prefix) to attach for a
    vision-capable model (see list_models()' "vision" capability tag) -- passed through in
    Ollama's own multimodal shape (`images` on the user message), which is what Open WebUI's
    `/api/chat/completions` proxies to Ollama as-is. Ignored (not an error) if the model doesn't
    support vision -- Ollama itself decides whether to use it."""
    user_message: dict = {"role": "user", "content": prompt}
    if image_b64:
        user_message["images"] = [image_b64] if isinstance(image_b64, str) else list(image_b64)

    messages = []
    if system:
        messages.append({"role": "system", "content": system})
    messages.append(user_message)

    return chat_messages(messages, model=model, temperature=temperature, timeout=timeout, base_url=base_url)


def chat(
    prompt: str,
    model: str = DEFAULT_MODEL,
    system: str | None = None,
    temperature: float = 0.2,
    timeout: float = 60.0,
    base_url: str | None = None,
) -> str:
    """One-shot chat completion. Returns the assistant's raw text -- caller decides whether/how
    to tag it as a draft (see LLM_DRAFT_TAG) before it touches any real file. Thin wrapper around
    chat_full() for callers that don't need usage stats or image input."""
    return chat_full(prompt, model=model, system=system, temperature=temperature,
                      timeout=timeout, base_url=base_url)["content"]


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("prompt", nargs="?", help="Prompt text (omit with --list-models)")
    ap.add_argument("--model", default=DEFAULT_MODEL, help=f"Model id (default: {DEFAULT_MODEL})")
    ap.add_argument("--system", default=None, help="Optional system prompt")
    ap.add_argument("--list-models", action="store_true", help="List available models and exit")
    args = ap.parse_args()

    try:
        if args.list_models:
            for m in list_models():
                details = m.get("ollama", {}).get("details", {})
                caps = m.get("ollama", {}).get("capabilities", [])
                print(f"{m['id']:24s} {details.get('parameter_size', ''):>8s}  {caps}")
            return

        if not args.prompt:
            ap.error("prompt is required unless --list-models is given")

        print(chat(args.prompt, model=args.model, system=args.system))
    except LLMClientError as e:
        print(f"error: {e}", file=sys.stderr)
        sys.exit(1)


if __name__ == "__main__":
    main()
