"""Atmacite Refiner warp destinations: the validation checklist and the Lua export.

Source of truth is data/voidwatch/refiner_warps.json (edited from the Voidwatch page). `export_lua()` renders it into
scripts/globals/voidwatch_warps.lua in the DSP script checkout, which the refiner script reads. Entries with a blank option/zone/coordinate
are exported as comments only, so an unfilled entry can never warp a player. Never fill an option or coordinate by guess.
"""
from __future__ import annotations

import datetime
import json
import re
from pathlib import Path

from workbench.runtime.paths import REPO_ROOT

from . import details as D

WARPS = REPO_ROOT / "data" / "voidwatch" / "refiner_warps.json"
LUA_REL = Path("scripts") / "globals" / "voidwatch_warps.lua"
EDITABLE = {"option": int, "zone": str, "x": float, "y": float, "z": float, "rot": int, "landing_note": str, "coord_source": str, "validation": str, "note": str}
VSTATES = ["untested", "ok", "bad", "needs-work"]


def load() -> list:
    return json.loads(WARPS.read_text(encoding="utf-8"))


def _norm(s: str) -> str:
    return re.sub(r"[^a-z0-9]", "", s.lower())


def overview(conn) -> dict:
    from workbench.server_admin.synth import recipes as R
    ids = {_norm(r[1]): int(r[0]) for r in R._rows(conn, "SELECT zoneid,name FROM zone_settings")}
    rows = load()
    for e in rows:
        e["zone_id"] = ids.get(_norm(e["zone"])) if e["zone"] else None
        e["complete"] = bool(e["option"] is not None and e["zone_id"] is not None and None not in (e["x"], e["y"], e["z"], e["rot"]))
    return {"warps": rows, "states": VSTATES, "total": len(rows), "complete": sum(1 for e in rows if e["complete"]),
            "ok": sum(1 for e in rows if e["validation"] == "ok"), "lua": str(LUA_REL)}


def save(wid: str, changes: dict, who: str = "") -> dict:
    rows = load()
    e = next((r for r in rows if r["id"] == wid), None)
    if e is None:
        raise KeyError(wid)
    for k, v in changes.items():
        if k not in EDITABLE:
            continue
        if v in ("", None):
            e[k] = None if EDITABLE[k] is not str else ""
        else:
            e[k] = EDITABLE[k](v)
    if e["validation"] not in VSTATES:
        e["validation"] = "untested"
    e["updated"] = datetime.datetime.now().isoformat(timespec="seconds")
    e["by"] = who
    tmp = WARPS.with_suffix(".tmp")
    tmp.write_text(json.dumps(rows, indent=1), encoding="utf-8")
    tmp.replace(WARPS)
    return e


def render_lua(conn) -> str:
    d = overview(conn)
    out = ["-- GENERATED by mission_toolkit (Voidwatch > Atmacite warp checklist). Do not hand-edit; edit in the toolkit and re-export.",
           "-- Entries missing an option id, zone id or coordinate are comments only and never warp.",
           "-- Option = (destId * 65536) + 2 as sent by the client in onEventFinish [C-log]; era: present / past ([S]).",
           "VWO_WARPS = {"]
    for e in d["warps"]:
        head = "-- %s %s %s %d: %s%s" % (e["era"], e["stone"], e["set"], e["tier"], e["menu"], (" (" + e["landing_note"] + ")") if e["landing_note"] else "")
        if e["complete"] and e["validation"] == "ok":
            out.append("    " + head)
            out.append("    [%d] = {era = \"%s\", stone = \"%s\", tier = %d, zone = %d, x = %s, y = %s, z = %s, rot = %d}," %
                       (e["option"], e["era"], e["stone"], e["tier"], e["zone_id"], e["x"], e["y"], e["z"], e["rot"]))
        else:
            why = "incomplete" if not e["complete"] else "not validated (" + e["validation"] + ")"
            out.append("    " + head + " -- SKIPPED: " + why)
    out.append("};")
    return "\n".join(out) + "\n"


def export_lua(conn, root: Path) -> dict:
    text = render_lua(conn)
    path = Path(root) / LUA_REL
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8", newline="\n")
    return {"path": str(path), "entries": text.count("] = {")}


# ---- paste imports (server log lines) -------------------------------------------------------------------------------------------------
_OPT_RE = re.compile(r"\[VWO refiner\] unhandled option=(\d+)[^\n]*?char=(\S+)\s+zone=(\d+)")
_POS_RE = re.compile(r"LOGPOS,([^,\n]*),(\d+),(-?[\d.]+),(-?[\d.]+),(-?[\d.]+),(\d+)")


def parse_options(text: str) -> list:
    """Option ids from '[VWO refiner] unhandled option=N' log lines, in order, duplicates removed. Only (destId<<16)|2 teleports are kept."""
    seen, out = set(), []
    for m in _OPT_RE.finditer(text):
        o = int(m.group(1))
        if o in seen or (o & 0xFFFF) != 2:
            continue
        seen.add(o)
        out.append({"option": o, "dest_id": o >> 16, "char": m.group(2), "refiner_zone": int(m.group(3))})
    return out


def parse_logpos(text: str) -> list:
    return [{"label": m.group(1), "zone_id": int(m.group(2)), "x": float(m.group(3)), "y": float(m.group(4)), "z": float(m.group(5)), "rot": int(m.group(6))}
            for m in _POS_RE.finditer(text)]


def import_text(conn, kind: str, wid: str, text: str, who: str = "") -> dict:
    """Apply the FIRST parsed record of the pasted text to warp `wid`. Options must be unique across entries; logpos sets zone + x/y/z/rot."""
    if kind == "option":
        recs = parse_options(text)
        if not recs:
            raise ValueError("no '[VWO refiner] unhandled option=' teleport line found in the pasted text")
        opt = recs[0]["option"]
        other = next((r for r in load() if r.get("option") == opt and r["id"] != wid), None)
        if other:
            raise ValueError("option %d is already assigned to %s (%s)" % (opt, other["id"], other["menu"]))
        return {"entry": save(wid, {"option": opt, "note": "option from pasted server log [C-log]"}, who), "found": len(recs)}
    if kind == "logpos":
        recs = parse_logpos(text)
        if not recs:
            raise ValueError("no LOGPOS,label,zone,x,y,z,rot line found in the pasted text")
        r = recs[0]
        from workbench.server_admin.synth import recipes as R
        zr = R._rows(conn, "SELECT name FROM zone_settings WHERE zoneid=%s", (r["zone_id"],))
        if not zr:
            raise ValueError("unknown zone id %d" % r["zone_id"])
        ch = {"zone": zr[0][0], "x": r["x"], "y": r["y"], "z": r["z"], "rot": r["rot"], "coord_source": "!logpos %s (in game)" % r["label"]}
        return {"entry": save(wid, ch, who), "found": len(recs)}
    raise ValueError("kind must be option or logpos")
