"""Atmacite Refiner warp destinations: the validation checklist and the Lua export.

Source of truth is data/voidwatch/refiner_warps.json (edited from the Voidwatch page). `export_lua()` renders it into
scripts/globals/voidwatch_warps.lua in the DSP script checkout, which the refiner script reads. Entries with a blank option/zone/coordinate
are exported as comments only, so an unfilled entry can never warp a player. Never fill an option or coordinate by guess.
"""
from __future__ import annotations

import datetime
import json
import re
from pathlib import Path

from workbench.runtime.paths import REPO_ROOT

from . import details as D

WARPS = REPO_ROOT / "data" / "voidwatch" / "refiner_warps.json"
LUA_REL = Path("scripts") / "globals" / "voidwatch_warps.lua"
EDITABLE = {"option": int, "zone": str, "x": float, "y": float, "z": float, "rot": int, "landing_note": str, "coord_source": str, "validation": str, "note": str}
VSTATES = ["untested", "ok", "bad", "needs-work"]


def load() -> list:
    return json.loads(WARPS.read_text(encoding="utf-8"))


def _norm(s: str) -> str:
    return re.sub(r"[^a-z0-9]", "", s.lower())


def overview(conn) -> dict:
    from workbench.server_admin.synth import recipes as R
    ids = {_norm(r[1]): int(r[0]) for r in R._rows(conn, "SELECT zoneid,name FROM zone_settings")}
    rows = load()
    for e in rows:
        e["zone_id"] = ids.get(_norm(e["zone"])) if e["zone"] else None
        e["complete"] = bool(e["option"] is not None and e["zone_id"] is not None and None not in (e["x"], e["y"], e["z"], e["rot"]))
    return {"warps": rows, "states": VSTATES, "total": len(rows), "complete": sum(1 for e in rows if e["complete"]),
            "ok": sum(1 for e in rows if e["validation"] == "ok"), "lua": str(LUA_REL)}


def save(wid: str, changes: dict, who: str = "") -> dict:
    rows = load()
    e = next((r for r in rows if r["id"] == wid), None)
    if e is None:
        raise KeyError(wid)
    for k, v in changes.items():
        if k not in EDITABLE:
            continue
        if v in ("", None):
            e[k] = None if EDITABLE[k] is not str else ""
        else:
            e[k] = EDITABLE[k](v)
    if e["validation"] not in VSTATES:
        e["validation"] = "untested"
    e["updated"] = datetime.datetime.now().isoformat(timespec="seconds")
    e["by"] = who
    tmp = WARPS.with_suffix(".tmp")
    tmp.write_text(json.dumps(rows, indent=1), encoding="utf-8")
    tmp.replace(WARPS)
    return e


def render_lua(conn) -> str:
    d = overview(conn)
    out = ["-- GENERATED by mission_toolkit (Voidwatch > Atmacite warp checklist). Do not hand-edit; edit in the toolkit and re-export.",
           "-- Entries missing an option id, zone id or coordinate are comments only and never warp.",
           "-- Option = (destId * 65536) + 2 as sent by the client in onEventFinish [C-log]; era: present / past ([S]).",
           "VWO_WARPS = {"]
    for e in d["warps"]:
        head = "-- %s %s %s %d: %s%s" % (e["era"], e["stone"], e["set"], e["tier"], e["menu"], (" (" + e["landing_note"] + ")") if e["landing_note"] else "")
        if e["complete"] and e["validation"] == "ok":
            out.append("    " + head)
            out.append("    [%d] = {era = \"%s\", stone = \"%s\", tier = %d, zone = %d, x = %s, y = %s, z = %s, rot = %d}," %
                       (e["option"], e["era"], e["stone"], e["tier"], e["zone_id"], e["x"], e["y"], e["z"], e["rot"]))
        else:
            why = "incomplete" if not e["complete"] else "not validated (" + e["validation"] + ")"
            out.append("    " + head + " -- SKIPPED: " + why)
    out.append("};")
    return "\n".join(out) + "\n"


def export_lua(conn, root: Path) -> dict:
    text = render_lua(conn)
    path = Path(root) / LUA_REL
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8", newline="\n")
    return {"path": str(path), "entries": text.count("] = {")}
