"""Regenerate src/workbench/editors/items/_enums_dsp.py from the DSP server headers (Mod, LATENT)."""
import re, sys
from pathlib import Path

from workbench.runtime.legacy_settings import get_dsp_root
from workbench.runtime.paths import REPO_ROOT

_dsp = get_dsp_root()
ROOT = Path(sys.argv[1]) if len(sys.argv) > 1 else ((_dsp / "src" / "map") if _dsp is not None else Path("D:/Claude/dsp-master/src/map"))

def parse(path, enum, prefix=''):
    s = open(path, encoding='utf-8-sig', errors='replace').read()
    m = re.search(r'enum\s+(?:class\s+)?' + enum + r'\b[^{]*\{(.*?)\n\};?', s, re.S)
    out, cur = {}, -1
    for line in m.group(1).splitlines():
        mm = re.match(r'\s*(\w+)\s*(?:=\s*([^,/]+?))?\s*,?\s*(?://\s*(.*))?$', line)
        if not mm or line.strip().startswith('//'):
            continue
        k, v, c = mm.groups()
        cur = int(v, 0) if v and re.fullmatch(r'-?(0x[0-9a-fA-F]+|\d+)', v.strip()) else (out_ids(out, v) if v else cur + 1)
        if k.startswith(prefix): k = k[len(prefix):]
        out[cur] = f'{k} -- {c.strip()}' if c and c.strip() else k
    return out

def out_ids(out, v):
    raise SystemExit(f'non-numeric enum value {v!r}')

mods = parse(f'{ROOT}/modifier.h', 'Mod')
lat = parse(f'{ROOT}/latent_effect.h', 'LATENT', 'LATENT_')
mog = parse(f'{ROOT}/items/item_furnishing.h', 'MOGHOUSE_AURA')
mog = {0: 'none', **{k: re.sub(r'^(\w+) -- (.*)$', lambda m: m.group(1).lower().replace('_', ' ') + ' (' + m.group(2).strip() + ')', v) for k, v in mog.items()}}
with open(REPO_ROOT / 'src/workbench/editors/items/_enums_dsp.py', 'w', encoding='utf-8', newline='\n') as f:
    f.write('"""GENERATED by scripts/maintenance/generate_dsp_item_enums.py from the DSP server headers (modifier.h Mod, latent_effect.h LATENT). Do not hand-edit."""\n')
    for n, d in (('MOD_NAMES', mods), ('LATENT_NAMES', lat), ('MOGHANCEMENT', mog)):
        f.write(f'{n} = {{\n')
        for k in sorted(d): f.write(f'    {k}: {d[k]!r},\n')
        f.write('}\n')
print(len(mods), len(lat), len(mog))
